### ISSUE TITLE
2.7 Eureka的高可用 - 这个章节会更新吗？

### ISSUE THREAD

**Issue by iamzhout** [eacdy/spring-cloud-book#4]
开个issue来问问题哈，勿怪。 

搜索的时候看到这个书，章节里面有提到2.7，但是还没来及写是吧？

**Comment by eacdy** [comment]
您好，感谢支持。
eureka的高可用在 2.1.2 Eureka的高可用
一开始规划的章节是2.7。后来做过多次的重新规划…笔误了，不好意思啊。感谢勘误哦。

目前忙着写spring cloud的实体书，由于与出版社约定12月底交稿，所以近期没怎么维护开源版。实体书的目录与开源版本完全不一样，所以暂时没有重新整理并发布。
等实体书出版后，其中的内容也会逐步汇入到开源版本中去。

敬请期待。

**Comment by iamzhout** [comment]
看到了，多谢回复。
