### ISSUE TITLE
链接 404

### ISSUE THREAD

**Issue by xiaoCong2014** [eacdy/spring-cloud-book#6]
文档里提到的"Spring Cloud所有的配置项" 的链接 404 :
http://cloud.spring.io/spring-cloud-static/Brixton.SR5/#_appendix_compendium_of_configuration_properties
这链接写于 https://eacdy.gitbooks.io/spring-cloud-book/content/2%20Spring%20Cloud/2%20Spring%20Cloud.html

**Comment by eacdy** [comment]
@xiaoCong2014 您好，感谢指正。这个系列太老了，还是基于Brixton的，这个版本Spring官方已经停止维护了，所以地址下掉了。
我目前正在基于最新的Spring Cloud Finchley重写，目前在博客连载：<http://www.itmuch.com/spring-cloud/spring-cloud-index/>，完稿后，也会同步到本仓库。
